esphome:
  name: panopticon-co2
  friendly_name: Panopticon CO2

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: 6.8.1
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

i2c:
  sda: GPIO12
  scl: GPIO13
  scan: false

uart:
  - id: motion_bus
    tx_pin: GPIO21
    rx_pin: GPIO22
    baud_rate: 9600
  - id: co2_bus
    tx_pin: GPIO19
    rx_pin: GPIO18
    baud_rate: 9600

ld2410:
  - uart_id: motion_bus
light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO08
    num_leds: 1
    chipset: WS2812
    rmt_symbols: 48
    id: "led_1"
    name: "Board LED"
    icon: "mdi:led-outline"
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: presence
    has_moving_target:
      name: Moving Target
      id: motion
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb
sensor:
  - platform: template
    name: Temperature_F
    id: temperature_f
    lambda: return id(temperature).state * 9/5+32;
    update_interval: 60s
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
      id: temperature
    pressure:
      name: "BME680 Pressure"
      id: pressure
    humidity:
      name: "BME680 Humidity"
      id: humidity
    gas_resistance:
      name: "BME680 Gas Resistance"
      id: gasresist
    address: 0x77
    update_interval: 60s
  - platform: mhz19
    id: mhz19s
    uart_id: co2_bus
    co2:
      name: MH-Z19 CO2 Value
      id: co2
    temperature:
      name: MH-Z19 Temperature
      id: temp2
  - platform: ld2410
    light:
      name: light
      id: ldlux
    moving_distance:
      name: Moving Distance
      id: mdistance 
    still_distance:
      name: Still Distance
      id: sdistance 
    moving_energy:
      name: Move Energy
      id: menergy
    still_energy:
      name: Still Energy
      id: senergy
    detection_distance:
      name: Detection Distance
      id: ddistance
switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
      id: emode
      restore_mode: ALWAYS_OFF
    bluetooth:
      name: "control bluetooth"
      id: bmode
      restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 
      number: GPIO10
    id: pms_set
    name: "Start measuring"

interval:
  - interval: 120s
    then:
      - switch.turn_on: pms_set
      - delay: 20s
      - switch.turn_off: pms_set

font:
  - file:
      type: gfonts
      family: Roboto
    id: roboto_14
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(roboto_14), "%.1f°C / %.1f ppm",  id(temp2).state, id(co2).state ); 
      it.printf(0, 14, id(roboto_14), "%.1f°F / %.1f%%",  id(temperature_f).state, id(humidity).state ); 
      it.printf(0, 30, id(roboto_14), "%.0f %.0f" ,  id(gasresist).state, id(pressure).state );
      it.printf(0, 48, id(roboto_14), "%.0f cm",  id(ddistance).state);  

external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

globals:
  - id: color_x
    type: float
    restore_value: no
    initial_value: '0'
  - id: color_y
    type: float
    restore_value: no
    initial_value: '0'

zigbee:
  id: "zb"
  router: true
  endpoints:
    - device_type: SIMPLE_SENSOR
      num: 1
      clusters:
        - id: OCCUPANCY_SENSING
          attributes:
            - id: zb_occupancy # actual state as bit. 0 -> empty; 1 -> occupied 
              attribute_id: 0x000
              type: 8BITMAP
              report: true
              value: 0
              device: presence
              lambda: !lambda "return x ? 1 : 0;" # perhaps not needed
            - attribute_id: 0x0001
              type: 8BIT_ENUM
              report: true
              value: 0x02 #0x00 -> PIR; 0x01 -> sonic; 0x02 -> PIR & sonic
        - id: ILLUMINANCE_MEASUREMENT
          attributes:
            - attribute_id: 0
              type: U16
              report: true
              value: 0
              device: ldlux
              lambda: !lambda "return log10(x)*10000 + 1;"
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temp2
              scale: 100
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 3
              report: true
              value: CO2
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: co2
              value: 100
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 96 # == ppm
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0

             
    - num: 2
      device_type: COLOR_DIMMABLE_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              on_value:
                then:
                  - light.control:
                      id: led_1
                      state: !lambda "return (bool)x;"
        - id: LEVEL_CONTROL
          attributes:
            - attribute_id: 0
              type: U8
              on_value:
                then:
                  - light.control:
                      id: led_1
                      brightness: !lambda "return ((float)x)/255;"    
        - id: COLOR_CONTROL
          attributes:
            - attribute_id: 3
              type: U16
              on_value:
                then:
                  - lambda: id(color_x) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
            - attribute_id: 4
              type: U16
              on_value:
                then:
                  - lambda: id(color_y) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
    - device_type: SIMPLE_SENSOR
      num: 3
      clusters:
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 6
              report: true
              value: Motion
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: bool
              device: motion
              report: true
    - device_type: TEMPERATURE_SENSOR
      num: 4
      clusters:
        - id: REL_HUMIDITY_MEASUREMENT
          attributes:
            - attribute_id: 0
              device: humidity
              type: U16
              report: true
              value: 100
              scale: 100
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temperature
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 0x8000
              device: pressure
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 14
              report: true
              value: Gas Resistance
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: gasresist
              value: 100
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 4 # == ohm
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
    - num: 5
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5
              report: true
              value: EMODE
            - attribute_id: 0
              type: bool
              on_value:
                then:   
                  - switch.turn_on: emode
    - num: 6
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5
              report: true
              value: BMODE
            - attribute_id: 0
              type: bool
              on_value:
                then:   
                  - switch.turn_on: bmode       
    - device_type: SIMPLE_SENSOR
      num: 7
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 11
              report: true
              value: Move Energy
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: menergy
              value: 100
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 98 # == generic & use BACNet Engineering Unit Enumeration List
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
    - device_type: SIMPLE_SENSOR
      num: 8
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 11
              report: true
              value: Target Dist
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: ddistance
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 118 # == centemeters
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
    - device_type: SIMPLE_SENSOR
      num: 9
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 12
              report: true
              value: Still Energy
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: senergy
              value: 100
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 98 # == generic & 
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
    - device_type: SIMPLE_SENSOR
      num: 10
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 10    #  This needs to match character count of value below
              report: true
              value: Move Dist.    #  Sensor Name
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: mdistance    #  Sensor ID defined earlier
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 118     # centimeters
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0 
