esphome:
  name: panopticon-lux
  friendly_name: panopticon-lux

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

i2c:
  sda: GPIO12
  scl: GPIO13
  scan: false
  id: bus_1

uart:
  - id: motion_bus
    tx_pin: GPIO21
    rx_pin: GPIO22
    baud_rate: 9600

ld2410:
  - uart_id: motion_bus

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO08
    num_leds: 1
    chipset: WS2812
    rmt_symbols: 48
    id: "led_1"
    name: "Board LED"
    icon: "mdi:led-outline"
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: presence
    has_moving_target:
      name: Moving Target
      id: motion
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb
sensor:
  - platform: bme280_i2c
    temperature:
      name: "Temperature"
      id: temperature
    pressure:
      name: "Pressure"
      id: pressure
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x76
    update_interval: 120s

  - platform: bh1750
    name: "BH1750 Illuminance"
    id: lux1
    address: 0x23
    update_interval: 120s

  - platform: ld2410
    light:
      name: light
      id: ldlux
    moving_distance:
      name: Moving Distance
      id: mdistance 
    still_distance:
      name: Still Distance
      id: sdistance 
    moving_energy:
      name: Move Energy
      id: menergy
    still_energy:
      name: Still Energy
      id: senergy
    detection_distance:
      name: Detection Distance
      id: ddistance

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
      id: emode
      restore_mode: RESTORE_DEFAULT_OFF
    bluetooth:
      name: "control bluetooth"
      id: bmode
      restore_mode: RESTORE_DEFAULT_OFF


external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

globals:
  - id: color_x
    type: float
    restore_value: no
    initial_value: '0'
  - id: color_y
    type: float
    restore_value: no
    initial_value: '0'

zigbee:
  id: "zb"
  router: true
  endpoints:
    - device_type: SIMPLE_SENSOR
      num: 1
      clusters:
        - id: OCCUPANCY_SENSING
          attributes:
            - id: zb_occupancy # actual state as bit. 0 -> empty; 1 -> occupied 
              attribute_id: 0x000
              type: 8BITMAP
              report: true
              value: 0
              device: presence
              lambda: !lambda "return x ? 1 : 0;" # perhaps not needed
            - attribute_id: 0x0001
              type: 8BIT_ENUM
              report: true
              value: 0x02 #0x00 -> PIR; 0x01 -> sonic; 0x02 -> PIR & sonic
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 6
              report: true
              value: Motion
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: bool
              device: motion
              report: true
    - num: 2
      device_type: COLOR_DIMMABLE_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              on_value:
                then:
                  - light.control:
                      id: led_1
                      state: !lambda "return (bool)x;"
        - id: LEVEL_CONTROL
          attributes:
            - attribute_id: 0
              type: U8
              on_value:
                then:
                  - light.control:
                      id: led_1
                      brightness: !lambda "return ((float)x)/255;"    
        - id: COLOR_CONTROL
          attributes:
            - attribute_id: 3
              type: U16
              on_value:
                then:
                  - lambda: id(color_x) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
            - attribute_id: 4
              type: U16
              on_value:
                then:
                  - lambda: id(color_y) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
    - device_type: TEMPERATURE_SENSOR
      num: 3
      clusters:
        - id: REL_HUMIDITY_MEASUREMENT
          attributes:
            - attribute_id: 0
              device: humidity
              type: U16
              report: true
              value: 100
              scale: 100
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temperature
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 0x8000
              device: pressure
        - id: ILLUMINANCE_MEASUREMENT
          attributes:
            - attribute_id: 0
              type: U16
              report: true
              value: 0
              device: lux1
              lambda: !lambda "return log10(x)*10000 + 1;"
    - num: 4
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5
              report: true
              value: EMODE
            - attribute_id: 0
              type: bool
              on_value:
                then:   
                  - switch.turn_on: emode
    - num: 5
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5
              report: true
              value: BMODE
            - attribute_id: 0
              type: bool
              on_value:
                then:   
                  - switch.turn_on: bmode
    - device_type: SIMPLE_SENSOR
      num: 6
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 11
              report: true
              value: Target Dist
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: ddistance
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 118 # == centemeters
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
