esphome:
  name: panopticon-lux-bsec2
  friendly_name: panopticon-lux-bsec2
  on_boot:
    - priority: 10
      then:
        lambda: |-
          id(bmode).turn_off();       # Turns of engineering and bluetooth modes at boot. Use the zigbee switches to enable, turn off switch then reboot to disable.
          id(emode).turn_off();       # Bluetooth mode is disabled by default to reduce EMF and help with network performance. Engineering mode is disabled to free system resources and reduce power.
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  partitions: partitions_zb.csv
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      
i2c:
  sda: GPIO12
  scl: GPIO13
  scan: false
  id: bus_1

uart:
  - id: motion_bus
    tx_pin: GPIO21
    rx_pin: GPIO22
    baud_rate: 9600

ld2410:
  - uart_id: motion_bus

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO08
    num_leds: 1
    chipset: WS2812
    rmt_symbols: 48
    id: "led_1"
    name: "Board LED"
    icon: "mdi:led-outline"
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
binary_sensor:
  - platform: ld2410
    has_target:
      name: Target
      id: target
    has_moving_target:
      name: Moving Target
      id: motion
    has_still_target:
      name: Still Target
      id: starget
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: ULP
  supply_voltage: 3.3V

sensor:
  - platform: template
    name: Temperature_F   # This is for the display only. You can omit this if you're not from the USA. Be sure to adjust the display lambda if you are all metric.
    filters:
        - round: 1
    id: temperature_f
    lambda: return id(temperature).state * 9/5+32;
    update_interval: 120s
  - platform: template
    id: qualnum1
    lambda: |-
      return static_cast<int>(std::atoi(id(qualnum).state.c_str()));
    update_interval: 125s     # Increase this interval if your device is too chatty.
    on_value:
      then:
        - zigbee.setAttr:
            id: setqual
            value: !lambda "return x;"
        - zigbee.report: zb       # For whatever reason, this is necessary or the sensor never updates
  - platform: template
    id: accunum1
    lambda: |-
      return static_cast<int>(std::atoi(id(accunum).state.c_str()));
    update_interval: 300s   # Increase this interval if your device is too chatty.
    on_value:
      then:
        - zigbee.setAttr:
            id: setaccu
            value: !lambda "return x;"
  - platform: bme68x_bsec2
    temperature:
      name: "BME680 Temperature"
      id: temperature
      filters:
        - round: 1
    pressure:
      name: "BME680 Pressure"
      id: pressure
      filters:
        - round: 1
    humidity:
      name: "BME680 Humidity"
      id: humidity
      filters:
        - round: 1
    gas_resistance:
      name: "BME680 Gas Resistance"
      id: gasresist
      filters:
        - round: 1   # These filters do nothing. You can probably omit these.
    iaq:
      name: "BME68x IAQ"
      id: iaq
      filters:
        - round: 1

  - platform: bh1750
    name: "BH1750 Illuminance"
    id: lux1
    address: 0x23
    update_interval: 120s
    filters:
      - round: 1

  - platform: ld2410
    light:
      name: light
      id: ldlux
      filters:
        - round: 1
    moving_distance:
      name: Moving Distance
      id: mdistance 
      filters:
        - round: 1
    still_distance:
      name: Still Distance
      id: sdistance 
      filters:
        - round: 1
    moving_energy:
      name: Move Energy
      id: menergy
      filters:
        - round: 1
    still_energy:
      name: Still Energy
      id: senergy
      filters:
        - round: 1
    detection_distance:
      name: Detection Distance
      id: ddistance
      filters:
        - round: 1

text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "BME68x IAQ Accuracy"
      id: accuracy
  - platform: template
    id: quality
    name: "BME68x IAQ Classification"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"OK"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Fair"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Poor"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Bad"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Very Bad!"};
      }
      else {
        return {"error"};
      }
  - platform: template
    id: qualnum
    name: "IAQ %"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"100"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"90"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"80"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"70"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"50"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"25"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"0"};
      }
      else {
        return {"1"};
      }
  - platform: template
    id: accunum
    name: "Accuracy %"
    lambda: |-
      if (id(accuracy).state == "Calibrated") {
        return {"100"};
      }
      else if (id(accuracy).state == "Calibrating") {
        return {"50"};
      }
      else if (id(accuracy).state == "Stabilizing") {
        return {"2"};
      }
      else if (id(accuracy).state == "Uncertain") {
        return {"25"};
      }
      else {
        return {"1"};
      }

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" # Enable this if the sensor gets stuck or you need to troubleshoot
      id: emode
    bluetooth:
      name: "control bluetooth" # Enable this to adjust sensitivity and other options using the HLKRadarTool app.
      id: bmode

font:
  - file:
      type: gfonts
      family: Roboto
    id: roboto_14
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(roboto_14), "%.0f lux /%.0f hPa",  id(lux1).state, id(pressure).state); 
      it.printf(0, 14, id(roboto_14), "%.1f°F/%.1f%%",  id(temperature_f).state, id(humidity).state); 
      it.printf(0, 30, id(roboto_14), "IAQ: %.0f   %s",  id(iaq).state, id(quality).state.c_str());
      it.printf(0, 48, id(roboto_14), "%s  %.0f cm",  id(accuracy).state.c_str(), id(ddistance).state);  

external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

globals:
  - id: color_x
    type: float
    restore_value: no
    initial_value: '0'
  - id: color_y
    type: float
    restore_value: no
    initial_value: '0'

zigbee:
  id: "zb"
  router: true
  endpoints:
    - device_type: SIMPLE_SENSOR
      num: 1
      clusters:
        - id: OCCUPANCY_SENSING
          attributes:
            - id: zb_occupancy # actual state as bit. 0 -> empty; 1 -> occupied 
              attribute_id: 0x000
              type: 8BITMAP
              report: true
              value: 0
              device: target
              lambda: !lambda "return x ? 1 : 0;" # perhaps not needed
            - attribute_id: 0x0001
              type: 8BIT_ENUM
              report: true
              value: 0x02 #0x00 -> PIR; 0x01 -> sonic; 0x02 -> PIR & sonic
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 6
              report: true
              value: Motion
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: bool
              device: motion
              report: true
    - num: 2
      device_type: COLOR_DIMMABLE_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              on_value:
                then:
                  - light.control:
                      id: led_1
                      state: !lambda "return (bool)x;"
        - id: LEVEL_CONTROL
          attributes:
            - attribute_id: 0
              type: U8
              on_value:
                then:
                  - light.control:
                      id: led_1
                      brightness: !lambda "return ((float)x)/255;"    
        - id: COLOR_CONTROL
          attributes:
            - attribute_id: 3
              type: U16
              on_value:
                then:
                  - lambda: id(color_x) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
            - attribute_id: 4
              type: U16
              on_value:
                then:
                  - lambda: id(color_y) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
    - device_type: TEMPERATURE_SENSOR
      num: 3
      clusters:
        - id: REL_HUMIDITY_MEASUREMENT
          attributes:
            - attribute_id: 0
              device: humidity
              type: U16
              report: true
              value: 100
              scale: 100
        - id: TEMP_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 100
              device: temperature
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: S16
              report: true
              value: 0x8000
              device: pressure
        - id: ILLUMINANCE_MEASUREMENT
          attributes:
            - attribute_id: 0
              type: U16
              report: true
              value: 0
              device: lux1
              lambda: !lambda "return log10(x)*10000 + 1;"
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 14
              report: true
              value: Gas Resistance
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: gasresist
              value: 100
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 4 # == ohm
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
    - num: 4
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5
              report: true
              value: EMODE
            - attribute_id: 0
              type: bool
              on_value:
                then:   
                  - switch.turn_on: emode
    - num: 5
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 5
              report: true
              value: BMODE
            - attribute_id: 0
              type: bool
              on_value:
                then:   
                  - switch.turn_on: bmode
    - device_type: SIMPLE_SENSOR
      num: 6
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 11
              report: true
              value: Target Dist
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: ddistance
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 118 # == centemeters
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 12
              report: true
              value: Still Target
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: bool
              device: starget
              report: true
    - device_type: SIMPLE_SENSOR
      num: 7
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 3
              report: true
              value: IAQ
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: iaq
              value: 100
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 95 # == count
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0 
    - device_type: SIMPLE_SENSOR
      num: 8
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 8
              report: true
              value: Accuracy
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              value: 100
              id: setaccu
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 98 # == generic percent
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0 
    - device_type: SIMPLE_SENSOR
      num: 9
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: CHAR_STRING
              max_length: 11
              report: true
              value: Air Quality
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              value: 100
              id: setqual
              report: true
            - attribute_id: 0x0075
              type: 16BIT_ENUM
              value: 98 # == generic percent
              report: true
            - attribute_id: 0x006F
              type: 8BITMAP
              value: 0
