esphome:
  name: panopticon-lux-bsec2
  friendly_name: panopticon-lux-bsec2
    
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
      
i2c:
  sda: GPIO12
  scl: GPIO13
  scan: false
  id: bus_1

uart:
  - id: motion_bus
    tx_pin: GPIO21
    rx_pin: GPIO22
    baud_rate: 9600
    parity: NONE
    stop_bits: 1

ld2410:
  - uart_id: motion_bus

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO08
    num_leds: 1
    chipset: WS2812
    rmt_symbols: 48
    id: "led_1"
    effects:
      - flicker
      - addressable_rainbow:
           speed: 3
           width: 100
      - addressable_twinkle:
          twinkle_probability: 35%
          progress_interval: 6ms
      - addressable_random_twinkle:
          twinkle_probability: 35%
          progress_interval: 6ms
      - addressable_fireworks:
          update_interval: 75ms
          spark_probability: 40%
          use_random_color: true
          fade_out_rate: 74
      - pulse:
          name: "SPulse"
          transition_length: 500ms
          update_interval: 2s
      - strobe:
          name: "Alarm"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 150ms
            - state: true
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              duration: 500ms
      - addressable_color_wipe:
          name: "BlueGradient"
          colors:
            - red: 0%
              green: 0%
              blue: 100%  
              num_leds: 10
              gradient: true
            - red: 0%
              green: 100%
              blue: 100%   
              num_leds: 10
              gradient: true
            - red: 100%
              green: 0%
              blue: 100%   
              num_leds: 15
              gradient: true
            - red: 0%
              green: 100%
              blue: 100%   
              num_leds: 10
              gradient: true
            - red: 0%
              green: 0%
              blue: 60%   
              num_leds: 2
              gradient: true
          add_led_interval: 250ms
          reverse: true
      - addressable_color_wipe:
          name: "RedGradient"
          colors:
            - red: 100%
              green: 91%
              blue: 0%  
              num_leds: 10
              gradient: true
            - red: 100%
              green: 6%
              blue: 18%   
              num_leds: 10
              gradient: true
            - red: 100%
              green: 63%
              blue: 0%   
              num_leds: 15
              gradient: true
            - red: 100%
              green: 60%
              blue: 18%   
              num_leds: 10
              gradient: true
            - red: 100%
              green: 0%
              blue: 0%   
              num_leds: 2
              gradient: true
          add_led_interval: 250ms
          reverse: true
          
binary_sensor:
  - platform: ld2410
    has_target:
      name: Target
      id: target
      filters:
        delayed_off: 45s
      on_press:   
        then:
          - zigbee.setAttr: { id: zb_occupancy, value: 1 }
          - zigbee.reportAttr: "zb_occupancy"
      on_release: 
        then:
          - zigbee.setAttr: { id: zb_occupancy, value: 0 }
          - zigbee.reportAttr: "zb_occupancy"
    has_moving_target:
      name: Moving Target
      id: motion
      filters:
        delayed_off: 45s
    has_still_target:
      name: Still Target
      id: starget
      filters:
        delayed_off: 45s
  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - zigbee.report: zb
    on_click:
      min_length: 5s
      max_length: 20s
      then:
        - zigbee.reset: zb

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: ULP
  supply_voltage: 3.3V

sensor:
  - platform: template
    name: Temperature_F  
    id: temperature_f
    lambda: return id(temperature).state * 9/5+32;
    filters:
        - round: 2
        - throttle: 60s
  - platform: bme68x_bsec2
    temperature:
      name: "BME680 Temperature"
      id: temperature
      filters:
        - round: 2
        - throttle: 60s
    pressure:
      name: "BME680 Pressure"
      id: pressure
      filters:
        - round: 2
        - throttle: 60s
    humidity:
      name: "BME680 Humidity"
      id: humidity
      filters:
        - round: 2
        - throttle: 60s
    gas_resistance:
      name: "BME680 Gas Resistance"
      id: gasresist
      filters:
        - round: 0
        - throttle: 60s
    iaq:
      name: "BME68x IAQ"
      id: iaq
      filters:
        - round: 0
        - throttle: 60s
    iaq_accuracy: 
      name: "BME680 IAQ Accuracy"
      id: iaqa
      filters:
        - round: 0
        - throttle: 60s
  - platform: bh1750
    name: "BH1750 Illuminance"
    id: lux1
    address: 0x23
    filters:
        - round: 0
        - throttle: 60s
  - platform: ld2410
    detection_distance:
      name: Detection Distance
      id: ddistance
      filters:
        - round: 0
        - throttle: 45s
text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "BME68x IAQ Accuracy"
      id: accuracy
  - platform: template
    id: quality
    name: "BME68x IAQ Classification"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"OK"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Fair"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Poor"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Bad"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Very Bad!"};
      }
      else {
        return {"error"};
      }

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
      id: emode
    bluetooth:
      name: "control bluetooth" 
      id: bmode

font:
  - file:
      type: gfonts
      family: Roboto
    id: roboto_14
    size: 14
    
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(roboto_14), "%.0f lux /%.0f hPa",  id(lux1).state, id(pressure).state); 
      it.printf(0, 14, id(roboto_14), "%.1f°F/%.1f%%",  id(temperature_f).state, id(humidity).state); 
      it.printf(0, 30, id(roboto_14), "IAQ: %.0f   %s",  id(iaq).state, id(quality).state.c_str());
      it.printf(0, 48, id(roboto_14), "%s  %.0f cm",  id(accuracy).state.c_str(), id(ddistance).state);  

external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

globals:
  - id: color_x
    type: float
    restore_value: no
    initial_value: '0'
  - id: color_y
    type: float
    restore_value: no
    initial_value: '0'

zigbee:
  id: "zb"
  router: false    #These devices work as a router, but you must switch to the v1.x tree to work reliably!
  power_supply: 1
  endpoints:
    - device_type: SIMPLE_SENSOR
      num: 1
      clusters:
        - id: OCCUPANCY_SENSING
          attributes:
            - id: zb_occupancy 
              attribute_id: 0x000
              type: MAP8
              report: true
              value: 0
              device: target
            - attribute_id: 0x0001
              type: ENUM8
              report: false
              value: 0x02 
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 0x001C
              type: STRING
              max_length: 6
              report: false
              value: Motion
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: bool
              device: motion
              report: true
        - id: ANALOG_OUTPUT  
          attributes:  
            - attribute_id: 0x001C  
              type: STRING  
              max_length: 4  
              report: false  
              value: Mode  
            - attribute_id: 0x0055    # PresentValue  
              type: SINGLE  
              access: READ_WRITE  
              value: 0  
              on_value:  
                then:  
                  - lambda: |-  
                      int mode = (int)x;  
                      if (mode == 0) {  
                        id(bmode).turn_off();   
                      } else if (mode == 1) {  
                        id(bmode).turn_on();   
                      } else if (mode >= 2) {  
                        id(emode).turn_on();      
                      }      
    - num: 2
      device_type: COLOR_DIMMABLE_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              on_value:
                then:
                  - light.control:
                      id: led_1
                      state: !lambda "return (bool)x;"
        - id: LEVEL
          attributes:
            - attribute_id: 0
              type: UINT8
              on_value:
                then:
                  - light.control:
                      id: led_1
                      brightness: !lambda "return ((float)x)/255;"    
        - id: COLOR_CONTROL
          attributes:
            - attribute_id: 3
              type: UINT16
              on_value:
                then:
                  - lambda: id(color_x) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
            - attribute_id: 4
              type: UINT16
              on_value:
                then:
                  - lambda: id(color_y) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
        - id: ANALOG_OUTPUT  
          attributes:  
            - attribute_id: 0x001C  
              type: STRING  
              max_length: 6  
              report: false  
              value: Effect  
            - attribute_id: 0x0055    # PresentValue  
              type: SINGLE  
              access: READ_WRITE  
              value: 0  
              on_value:  
                then:  
                  - if:  
                      condition:  
                        - lambda: 'return x == 0;'  
                      then:  
                        - light.turn_off: led_1  
                      else:  
                        - lambda: |-  
                            static const char* effects[] = {  
                              "None", "rainbow", "twinkle", "RedGradient",  
                              "BlueGradient", "flicker", "fireworks", "SPulse", "Alarm"  
                            };  
                            auto call = id(led_1).turn_on();  
                            call.set_effect(effects[(int)x]);  
                            call.perform();                      
    - device_type: TEMPERATURE_SENSOR
      num: 3
      clusters:
        - id: TEMPERATURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: UINT16
              report: true
              value: 100
              device: temperature
              scale: 100
        - id: REL_HUMIDITY_MEASUREMENT
          attributes:
            - attribute_id: 0
              device: humidity
              type: UINT16
              report: true
              value: 100
              scale: 100
        - id: PRESSURE_MEASUREMENT
          attributes:
            - attribute_id: 0x0
              type: UINT16
              report: true
              value: 0x8000
              device: pressure
        - id: ILLUMINANCE_MEASUREMENT
          attributes:
            - attribute_id: 0
              type: UINT16
              report: true
              value: 0
              device: lux1
              lambda: !lambda "return log10(x)*10000 + 1;"
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 14
              report: false
              value: Gas Resistance
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: gasresist
              value: 100
              report: true
            - attribute_id: 0x0075
              type: ENUM16
              value: 4 # == ohm
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0
    - device_type: SIMPLE_SENSOR
      num: 4
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 11
              report: false
              value: Target Dist
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: ddistance
            - attribute_id: 0x0075
              type: ENUM16
              value: 118 
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0
        - id: BINARY_INPUT
          attributes: 
            - attribute_id: 0x001C
              type: STRING
              max_length: 12
              report: false
              value: Still Target
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: bool
              device: starget
              report: true
    - device_type: SIMPLE_SENSOR
      num: 5
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 3
              report: false
              value: IAQ
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: iaq
              value: 100
              report: true
            - attribute_id: 0x0075
              type: ENUM16
              value: 95 
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0 
    - device_type: SIMPLE_SENSOR
      num: 6
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 8
              report: false
              value: Accuracy
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              value: 100
              device: iaqa
              report: true
            - attribute_id: 0x0075
              type: ENUM16
              value: 95 
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0 
