esphome:
  name: xiao-mmw-heartrate
  friendly_name: XIAO Presence and Heart Rate Detection

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf

light:
  - platform: esp32_rmt_led_strip
    id: led_1
    name: "Seeed MR60BHA2 RGB Light"
    pin: GPIO1
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812
    effects:
      - flicker
      - addressable_rainbow:
           speed: 3
           width: 100
      - addressable_twinkle:
          twinkle_probability: 35%
          progress_interval: 6ms
      - addressable_random_twinkle:
          twinkle_probability: 35%
          progress_interval: 6ms
      - addressable_fireworks:
          update_interval: 75ms
          spark_probability: 40%
          use_random_color: true
          fade_out_rate: 74
      - pulse:
          name: "SPulse"
          transition_length: 500ms
          update_interval: 2s
      - strobe:
          name: "Alarm"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 150ms
            - state: true
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              duration: 500ms
      - addressable_color_wipe:
          name: "BlueGradient"
          colors:
            - red: 0%
              green: 0%
              blue: 100%  
              num_leds: 10
              gradient: true
            - red: 0%
              green: 100%
              blue: 100%   
              num_leds: 10
              gradient: true
            - red: 100%
              green: 0%
              blue: 100%   
              num_leds: 15
              gradient: true
            - red: 0%
              green: 100%
              blue: 100%   
              num_leds: 10
              gradient: true
            - red: 0%
              green: 0%
              blue: 60%   
              num_leds: 2
              gradient: true
          add_led_interval: 250ms
          reverse: true
      - addressable_color_wipe:
          name: "RedGradient"
          colors:
            - red: 100%
              green: 91%
              blue: 0%  
              num_leds: 10
              gradient: true
            - red: 100%
              green: 6%
              blue: 18%   
              num_leds: 10
              gradient: true
            - red: 100%
              green: 63%
              blue: 0%   
              num_leds: 15
              gradient: true
            - red: 100%
              green: 60%
              blue: 18%   
              num_leds: 10
              gradient: true
            - red: 100%
              green: 0%
              blue: 0%   
              num_leds: 2
              gradient: true
          add_led_interval: 250ms
          reverse: true
          
i2c:
  sda: GPIO22
  scl: GPIO23
  scan: false
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Occupancy"
      id: sensor_occupancy
      filters:
        delayed_off: 45s
      on_press:   
        then:
          - zigbee.setAttr: { id: zb_occupancy, value: 1 }
          - zigbee.reportAttr: "zb_occupancy"
      on_release: 
        then:
          - zigbee.setAttr: { id: zb_occupancy, value: 0 }
          - zigbee.reportAttr: "zb_occupancy"
      
sensor:
  - platform: bh1750
    id: illum_id
    name: "Illuminance"
    address: 0x23
    filters:
        - round: 2
        - throttle: 60s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Respiratory rate"
      id: respirate
      filters:
        - round: 2
        - throttle: 60s
    heart_rate:
      name: "Heart rate"
      id: heart
      filters:
        - round: 2
        - throttle: 60s
    distance:
      name: "Distance to Target"
      id: distance
      filters:
        - round: 2
        - throttle: 60s
    num_targets:
      name: "Number of People Detected"
      id: people
      filters:
        - round: 0
        - throttle: 45s
        
# Remember: You MUST downgrade to /tree/v1.x if you plan on turning on the router function of this device!
external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

globals:
  - id: color_x
    type: float
    restore_value: no
    initial_value: '0'
  - id: color_y
    type: float
    restore_value: no
    initial_value: '0'

zigbee:
  id: "zb"
  router: false   # Routing performance of the XIAO C6 module is abysmal. Keep this as an end_device!
  power_supply: 1
  endpoints:
    - device_type: SIMPLE_SENSOR
      num: 1
      clusters:
        - id: OCCUPANCY_SENSING
          attributes:
            - id: zb_occupancy  
              attribute_id: 0x000
              type: MAP8
              report: true
              value: 0
              device: sensor_occupancy
            - attribute_id: 0x0001
              type: ENUM8
              report: false
              value: 0x01 # 0x00 -> PIR; 0x01 -> sonic; 0x02 -> PIR & sonic
        - id: ILLUMINANCE_MEASUREMENT
          attributes:
            - attribute_id: 0
              type: UINT16
              report: true
              value: 0
              lambda: !lambda "return log10(x)*10000 + 1;"
              device: illum_id             
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 13
              report: false
              value: Total Targets
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: people
              value: 100
              report: true
            - attribute_id: 0x0075
              type: ENUM16
              value: 95 # == count / no units
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0
    - num: 2
      device_type: COLOR_DIMMABLE_LIGHT
      clusters:
        - id: ON_OFF
          attributes:
            - attribute_id: 0
              type: bool
              on_value:
                then:
                  - light.control:
                      id: led_1
                      state: !lambda "return (bool)x;"
        - id: LEVEL
          attributes:
            - attribute_id: 0
              type: UINT8
              on_value:
                then:
                  - light.control:
                      id: led_1
                      brightness: !lambda "return ((float)x)/255;"    
        - id: COLOR_CONTROL
          attributes:
            - attribute_id: 3
              type: UINT16
              on_value:
                then:
                  - lambda: id(color_x) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
            - attribute_id: 4
              type: UINT16
              on_value:
                then:
                  - lambda: id(color_y) = (float)x/65536;
                  - light.control:
                      id: led_1
                      red: !lambda "return zigbee::get_r_from_xy(id(color_x), id(color_y));"
                      green: !lambda "return zigbee::get_g_from_xy(id(color_x), id(color_y));"
                      blue: !lambda "return zigbee::get_b_from_xy(id(color_x), id(color_y));"
        - id: ANALOG_OUTPUT  
          attributes:  
            - attribute_id: 0x001C  
              type: STRING  
              max_length: 6  
              report: false  
              value: Effect  
            - attribute_id: 0x0055    # PresentValue  
              type: SINGLE  
              access: READ_WRITE  
              value: 0  
              on_value:  
                then:  
                  - if:  
                      condition:  
                        - lambda: 'return x == 0;'  
                      then:  
                        - light.turn_off: led_1  
                      else:  
                        - lambda: |-  
                            static const char* effects[] = {  
                              "None", "rainbow", "twinkle", "RedGradient",  
                              "BlueGradient", "flicker", "fireworks", "SPulse", "Alarm"  
                            };  
                            auto call = id(led_1).turn_on();  
                            call.set_effect(effects[(int)x]);  
                            call.perform();
    - device_type: SIMPLE_SENSOR
      num: 3
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 10
              report: false
              value: Heart Rate
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: heart
              value: 100
              report: true
            - attribute_id: 0x0075
              type: ENUM16
              value: 100 # == per minute
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0
    - device_type: SIMPLE_SENSOR
      num: 4
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 11
              report: false
              value: Breath Rate
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              device: respirate
              value: 100
              report: true
            - attribute_id: 0x0075
              type: ENUM16
              value: 100 # == per minute
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0
    - device_type: SIMPLE_SENSOR
      num: 5
      clusters:
        - id:  ANALOG_INPUT
          attributes:
            - attribute_id: 0x001C
              type: STRING
              max_length: 11
              report: false
              value: Target Dist
            - attribute_id: 0x0051
              type: bool
              value: false
            - attribute_id: 0x0055
              type: single
              report: true
              value: 0
              device: distance
            - attribute_id: 0x0075
              type: ENUM16
              value: 118 # == centemeters
              report: false
            - attribute_id: 0x006F
              type: MAP8
              value: 0

button:
  - platform: template
    name: reset
    on_press:
      then:
        - zigbee.reset: zb
